In [1]:
import numpy as np

In [2]:
# 3 tokens, embedding size 4
X = np.array([
    [1, 0, 1, 0],   # "I"
    [0, 2, 0, 2],   # "love"
    [1, 1, 1, 1]    # "AI"
])

print("Input Shape:", X.shape)
print(X)

Input Shape: (3, 4)
[[1 0 1 0]
 [0 2 0 2]
 [1 1 1 1]]


In [3]:
np.random.seed(0)

# 3 words, each has 4 numbers (embedding size = 4)
X = np.random.rand(3, 4)

print("Input Shape:", X.shape)
print(X)

## each row is a token vector

Input Shape: (3, 4)
[[0.5488135  0.71518937 0.60276338 0.54488318]
 [0.4236548  0.64589411 0.43758721 0.891773  ]
 [0.96366276 0.38344152 0.79172504 0.52889492]]


In [4]:
# Dot product similarity
scores = X @ X.T
print("Raw Attention Scores:\n", scores)

Raw Attention Scores:
 [[1.47291346 1.44411773 1.56851324]
 [1.44411773 1.58340425 1.47402593]
 [1.56851324 1.47402593 1.98223169]]


In [5]:
print(scores.max())

1.9822316864033112


In [6]:
np.random.seed(0)  # for reproducibility

d_model = 4  # embedding size

# Random weight matrices (learnable in real models)
Wq = np.random.rand(d_model, d_model)
Wk = np.random.rand(d_model, d_model)
Wv = np.random.rand(d_model, d_model)

# Compute Q, K, V
Q = X @ Wq
K = X @ Wk
V = X @ Wv

print("Q shape:", Q.shape)
print("K shape:", K.shape)
print("V shape:", V.shape)

Q shape: (3, 4)
K shape: (3, 4)
V shape: (3, 4)


In [7]:
scores = Q @ K.T  ## Each word now has score with every word.
print("Raw Attention Scores:\n", scores)

Raw Attention Scores:
 [[7.98861399 7.79495585 8.41894656]
 [7.53836312 7.34664864 7.91993039]
 [8.8043471  8.60041193 9.23980575]]


In [8]:
dk = d_model
scaled_scores = scores / np.sqrt(dk)
print('Scaled Scores:\n',scaled_scores)

Scaled Scores:
 [[3.994307   3.89747792 4.20947328]
 [3.76918156 3.67332432 3.95996519]
 [4.40217355 4.30020597 4.61990287]]


In [9]:
def softmax(x):
    exp_x = np.exp(x)
    return exp_x / np.sum(exp_x, axis=1, keepdims=True)

attention_weights = softmax(scores)

print(attention_weights)

[[0.2974678  0.24509548 0.45743672]
 [0.30394021 0.25091558 0.44514421]
 [0.29751394 0.24262715 0.45985891]]


In [10]:
output = attention_weights @ V
print('Self-Attention Output:\n', output)

Self-Attention Output:
 [[1.30573367 1.44056503 1.11256195 0.92914676]
 [1.30562103 1.43956976 1.11409541 0.92814053]
 [1.30566018 1.44069962 1.11240515 0.92946367]]
